const lin=1234557547n;
const sum=lin+7n;
console.log(sum);
let data;
data=5;
data="My javascript program";
console.log(data);
console.log(typeof(data));
let x=5;
let y=6;
console.log(x<y);
let z=x>y;
console.log(z);
console.log(typeof(z));
let a=5;
console.log(a=='5');
console.log(a==='5');
var b=5;
 b+=5;
console.log(b);
b**=5;
console.log(b);