let a=["Stream",{},23,true];
console.log(a);
console.log(a[1]);
console.log(a[1]+a[2]);
console.log(a[2]+a[3]);
const len=a.length;
console.log(len);  
console.log(len-1); 
const c=new Array("apple","ball");
console.log(c);
console.log(typeof(c)); 
let h=["hello","operation","clarity","Tls"];
h.push("name");
console.log(h);
let memo=["Div","priya","Devi","mano"];
memo.push("work");
console.log(memo);
memo[6]="active";
console.log(memo);
memo.pop();
console.log(memo);
memo.shift();
console.log(memo);